// ================================================================
// IMMORTAIL™ Gen2 — MODEL PROFILES
// Static catalogue of supported providers + their known models.
// No API keys, no secrets, no runtime calls.
// ================================================================

export const PROVIDER_TYPES = {
  OPENAI:      'openai',
  GROQ:        'groq',
  OPENROUTER:  'openrouter',
  CLAUDE:      'claude',
  GEMINI:      'gemini',
  OLLAMA:      'ollama',
  LMSTUDIO:    'lmstudio',
  CUSTOM:      'custom',
};

export const PROVIDER_CATEGORIES = {
  LOCAL:  'local',
  CLOUD:  'cloud',
  CUSTOM: 'custom',
};

export const PROVIDER_CATALOGUE = [
  {
    typeId:       PROVIDER_TYPES.OLLAMA,
    name:         'Ollama',
    icon:         '🦙',
    category:     PROVIDER_CATEGORIES.LOCAL,
    badge:        'LOCAL',
    offlineSafe:  true,
    baseUrlDefault: 'http://localhost:11434',
    endpointPath: '/api/chat',
    modelsPath:   '/api/tags',
    authType:     'none',
    streamSupport: true,
    defaultModel: 'llama3',
    knownModels:  ['llama3', 'llama3:8b', 'llama3:70b', 'mistral', 'mixtral', 'phi3', 'gemma2', 'qwen2', 'deepseek-coder', 'codellama'],
    description:  'Local LLM — runs entirely on-device. Primary persistent brain.',
    docsUrl:      'https://ollama.com',
    capabilities: ['chat', 'embeddings', 'vision', 'offline'],
  },
  {
    typeId:       PROVIDER_TYPES.GROQ,
    name:         'Groq',
    icon:         '⚡',
    category:     PROVIDER_CATEGORIES.CLOUD,
    badge:        'FAST',
    offlineSafe:  false,
    baseUrlDefault: 'https://api.groq.com/openai/v1',
    endpointPath: '/chat/completions',
    modelsPath:   '/models',
    authType:     'bearer',
    streamSupport: true,
    defaultModel: 'llama3-8b-8192',
    knownModels:  ['llama3-8b-8192', 'llama3-70b-8192', 'llama-3.1-8b-instant', 'llama-3.3-70b-versatile', 'mixtral-8x7b-32768', 'gemma2-9b-it', 'meta-llama/llama-4-scout-17b-16e-instruct'],
    description:  'Ultra-fast cloud inference. Groq acceleration layer.',
    docsUrl:      'https://console.groq.com/keys',
    capabilities: ['chat', 'vision', 'fast'],
  },
  {
    typeId:       PROVIDER_TYPES.OPENAI,
    name:         'OpenAI',
    icon:         '🧠',
    category:     PROVIDER_CATEGORIES.CLOUD,
    badge:        'CLOUD',
    offlineSafe:  false,
    baseUrlDefault: 'https://api.openai.com/v1',
    endpointPath: '/chat/completions',
    modelsPath:   '/models',
    authType:     'bearer',
    streamSupport: true,
    defaultModel: 'gpt-4o',
    knownModels:  ['gpt-4o', 'gpt-4o-mini', 'gpt-4-turbo', 'gpt-4', 'gpt-3.5-turbo', 'o1', 'o1-mini', 'o3-mini'],
    description:  'GPT-4o series — strong emotional reasoning.',
    docsUrl:      'https://platform.openai.com/api-keys',
    capabilities: ['chat', 'vision', 'embeddings'],
  },
  {
    typeId:       PROVIDER_TYPES.OPENROUTER,
    name:         'OpenRouter',
    icon:         '🔀',
    category:     PROVIDER_CATEGORIES.CLOUD,
    badge:        'MULTI',
    offlineSafe:  false,
    baseUrlDefault: 'https://openrouter.ai/api/v1',
    endpointPath: '/chat/completions',
    modelsPath:   '/models',
    authType:     'bearer',
    streamSupport: true,
    defaultModel: 'meta-llama/llama-3-8b-instruct:free',
    knownModels:  ['meta-llama/llama-3-8b-instruct:free', 'meta-llama/llama-3.1-8b-instruct:free', 'mistralai/mistral-7b-instruct:free', 'google/gemma-2-9b-it:free', 'nousresearch/hermes-3-llama-3.1-405b'],
    description:  'Routes to 100+ models. Free tiers available.',
    docsUrl:      'https://openrouter.ai/keys',
    capabilities: ['chat', 'multi-provider', 'free-tier'],
  },
  {
    typeId:       PROVIDER_TYPES.CLAUDE,
    name:         'Anthropic',
    icon:         '🔬',
    category:     PROVIDER_CATEGORIES.CLOUD,
    badge:        'CLOUD',
    offlineSafe:  false,
    baseUrlDefault: 'https://api.anthropic.com/v1',
    endpointPath: '/messages',
    modelsPath:   null,
    authType:     'x-api-key',
    streamSupport: true,
    defaultModel: 'claude-3-5-haiku-20241022',
    knownModels:  ['claude-3-5-haiku-20241022', 'claude-3-5-sonnet-20241022', 'claude-3-opus-20240229', 'claude-3-sonnet-20240229', 'claude-3-haiku-20240307'],
    description:  'Claude 3 series — strong reasoning and emotional nuance.',
    docsUrl:      'https://console.anthropic.com/settings/keys',
    capabilities: ['chat', 'vision', 'reasoning'],
  },
  {
    typeId:       PROVIDER_TYPES.GEMINI,
    name:         'Google Gemini',
    icon:         '💎',
    category:     PROVIDER_CATEGORIES.CLOUD,
    badge:        'CLOUD',
    offlineSafe:  false,
    baseUrlDefault: 'https://generativelanguage.googleapis.com/v1beta',
    endpointPath: '/models/{model}:generateContent',
    modelsPath:   '/models',
    authType:     'query-key',
    streamSupport: true,
    defaultModel: 'gemini-1.5-flash',
    knownModels:  ['gemini-1.5-flash', 'gemini-1.5-pro', 'gemini-2.0-flash', 'gemini-pro'],
    description:  'Google Gemini — multimodal intelligence.',
    docsUrl:      'https://aistudio.google.com/app/apikey',
    capabilities: ['chat', 'vision', 'multimodal'],
  },
  {
    typeId:       PROVIDER_TYPES.LMSTUDIO,
    name:         'LM Studio',
    icon:         '🖥️',
    category:     PROVIDER_CATEGORIES.LOCAL,
    badge:        'LOCAL',
    offlineSafe:  true,
    baseUrlDefault: 'http://localhost:1234/v1',
    endpointPath: '/chat/completions',
    modelsPath:   '/models',
    authType:     'none',
    streamSupport: true,
    defaultModel: 'local-model',
    knownModels:  ['local-model'],
    description:  'LM Studio local server — OpenAI-compatible API.',
    docsUrl:      'https://lmstudio.ai',
    capabilities: ['chat', 'local', 'openai-compatible'],
  },
  {
    typeId:       PROVIDER_TYPES.CUSTOM,
    name:         'Custom Endpoint',
    icon:         '🔧',
    category:     PROVIDER_CATEGORIES.CUSTOM,
    badge:        'CUSTOM',
    offlineSafe:  false,
    baseUrlDefault: '',
    endpointPath: '/chat/completions',
    modelsPath:   '/models',
    authType:     'bearer',
    streamSupport: false,
    defaultModel: '',
    knownModels:  [],
    description:  'Any OpenAI-compatible endpoint.',
    docsUrl:      null,
    capabilities: ['chat', 'custom'],
  },
];

export const BADGE_STYLE = {
  LOCAL:  { background: '#0d2318', color: '#4ade80', border: '1px solid #4ade8033' },
  FAST:   { background: '#1a0d2e', color: '#c4b5fd', border: '1px solid #c4b5fd33' },
  CLOUD:  { background: '#1a0d0d', color: '#f87171', border: '1px solid #f8717133' },
  MULTI:  { background: '#1a1a0d', color: '#fbbf24', border: '1px solid #fbbf2433' },
  OPEN:   { background: '#0d1a2e', color: '#60a5fa', border: '1px solid #60a5fa33' },
  CUSTOM: { background: '#1a1420', color: '#a78bfa', border: '1px solid #a78bfa33' },
};

export const STATUS_COLORS = {
  online:   { color: '#4ade80', glow: '#4ade8066' },
  offline:  { color: '#f87171', glow: '#f8717166' },
  testing:  { color: '#fbbf24', glow: '#fbbf2466' },
  unknown:  { color: '#6b7280', glow: '#6b728066' },
  degraded: { color: '#fb923c', glow: '#fb923c66' },
};

export function getCatalogueEntry(typeId) {
  return PROVIDER_CATALOGUE.find(p => p.typeId === typeId) ?? PROVIDER_CATALOGUE.find(p => p.typeId === PROVIDER_TYPES.CUSTOM);
}

export function buildNewProvider(typeId, overrides = {}) {
  const cat = getCatalogueEntry(typeId);
  return {
    id:           `${typeId}_${Date.now()}`,
    typeId,
    name:         overrides.name      ?? cat.name,
    icon:         cat.icon,
    category:     cat.category,
    badge:        cat.badge,
    baseUrl:      overrides.baseUrl   ?? cat.baseUrlDefault,
    endpointPath: cat.endpointPath,
    authType:     cat.authType,
    apiKey:       overrides.apiKey    ?? '',
    selectedModel: overrides.model   ?? cat.defaultModel,
    streamSupport: cat.streamSupport,
    enabled:      overrides.enabled   ?? false,
    priority:     overrides.priority  ?? 50,
    status:       'unknown',
    latencyMs:    null,
    lastTestedAt: null,
    lastTestedResult: null,
    createdAt:    Date.now(),
    updatedAt:    Date.now(),
    testHistory:  [],
    capabilities: cat.capabilities,
    offlineSafe:  cat.offlineSafe,
    isBuiltIn:    overrides.isBuiltIn ?? false,
  };
}

/** Generate the 3 built-in providers that boot with fresh installs */
export function getDefaultProviders() {
  return [
    buildNewProvider(PROVIDER_TYPES.OLLAMA, { enabled: true, priority: 100, isBuiltIn: true }),
    buildNewProvider(PROVIDER_TYPES.GROQ,   { enabled: false, priority: 80, isBuiltIn: true }),
    buildNewProvider(PROVIDER_TYPES.OPENAI, { enabled: false, priority: 60, isBuiltIn: true }),
  ];
}
